name: RAG Base
on:
  workflow_dispatch:
  push:
    paths:
      - 'images/rag-base/**'
    branches:
      - main
  pull_request:
    paths:
      - 'images/rag-base/**'
    branches:
      - main

env:
  ICR_REGISTRY: icr.io
  ICR_NAMESPACE: ai-services-cicd

jobs:
  build-publish-image:
    name: Build and Publish Image â€” ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04-ppc64le
          - ubuntu-24.04-ppc64le-2xlarge
          - ubuntu-24.04-ppc64le-4xlarge
          - ubuntu-24.04-ppc64le-p10
          - ubuntu-24.04-ppc64le-2xlarge-p10
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Build rag-base image
        working-directory: images/rag-base
        run: |
          make build REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }}

      # - name: Publish rag-base image
      #   working-directory: images/rag-base
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     make push REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }} REGISTRY_USER=${{ secrets.ICR_USERNAME }} REGISTRY_PASSWORD=${{ secrets.ICR_APIKEY }}
